### PR TITLE
Opr839

### PR DESCRIPTION
**Pull request by jwag956**

### CODE REVIEW

**Comment by eregnier** [comment]
Looks good 👍  Thank you @jwag956 for help and improvements.

**Comment by eregnier** [comment]
@jwag956 it is cool you merged !
Do know when you will make a release with this PR ?

**Comment by jwag956** [comment]
3.2.0rc1 is up with your changes:
https://pypi.org/project/Flask-Security-Too/#history

**Comment by booherbg** [comment]
@jwag956 -- thanks for merging this in, I think it'll be useful for me. Curious, does this cover the case where a user changes their password? I think that would invalidate the token right? Or would the old token still "work" (in cache) until a new one is generated (via TTL timeout), thus this is a non-issue?

**Pull request merged**
