### PR TITLE
Made sure 2FA pages get translated as well

### PR DESCRIPTION
**Pull request by TaaviE**
I auto-formatted the 2FA templates and made sure they get translated

### CODE REVIEW

**Comment by TaaviE** [comment]
Squash merge would be nice to keep the changes contained in one commit, they're separate right now so some stuff could be cherry picked more easily if need to be.

**Comment by TaaviE** [comment]
I've updated my own project's strings with this small script:

```bash
#!/bin/bash
# Extract all strings
pybabel extract -F babel.ini -k lazy_gettext -o flask_security/translations/flask_security.pot .

# Update language files
pybabel update -i flask_security/translations/flask_security.pot -d flask_security/translations

# Compile all translations
#pybabel compile -d flask_security/translations
```

**Comment by jwag956** [comment]
is there any reason we shouldn't do that in master? I guess that might break some apps? or will it?

**Comment by TaaviE** [comment]
There should be no downsides to updating translation files, it shouldn't break anything. Untranslated strings are untranslated anyways.

**Pull request merged**
