### PR TITLE
Remove the use of `flask-peewee`

### LINKED ISSUE #199: Remove use of Flask-peewee
Flask-peewee is deprecated. The quickstart example doesn't work. And according to this:
https://github.com/mattupstate/flask-security/issues/849#issuecomment-549642127

it's easy to simply use base peewee.

### PR DESCRIPTION
**Pull request by nelsonkam**
This fixes #199

### CODE REVIEW

**Comment by jwag956** [comment]
Thanks for doing this - there is a bit more to do however - we should actually remove it from
usage - in tests and setup.py. Do you have time to do that?

**Comment by nelsonkam** [comment]
Hello, sorry for the late reply. My latest commit does just that, can you have a look and let me know if it looks good? 
I'm new to all things open source so forgive any misstep.

**Comment by jwag956** [comment]
Thanks!

Make sure you run:

python setup.py test  build_sphinx
to catch errors like flake8, unit tests, black, formatting.

**Comment by nelsonkam** [comment]
Thanks for the heads up. It's all done now.

**Pull request merged**
