### PR TITLE
Update translation.

### PR DESCRIPTION
**Pull request by miceno**
An update on catalan translation.

### CODE REVIEW

**Comment by miceno** [comment]
@jwag956 Thank you for your comments!!

I have reviewed the spelling and commit again.

I will wait for travis results and review them again.

**Comment by miceno** [comment]
Good! It passes the `ca_ES` spell checking. Please, merge the PR 👍

**Comment by jwag956** [comment]
@miceno Quick question for you - I am trying to wrap my head around just how flask, flask-babel, jinja all conspire to translates portions of a form. Do you have a repo that uses Flask-Security forms that you could share? or else would you be willing to answer some questions around how you configure your app (like are you using stock forms or extending them, any particular configuration around babel, etc?)

thanks.

**Comment by miceno** [comment]
I am using them from flask-admin using flask-babelex.For instance I have created custom forms for login and recover password, but only those.On Jun 17, 2019 19:00, Chris Wagner <notifications@github.com> wrote:@miceno Quick question for you - I am trying to wrap my head around just how flask, flask-babel, jinja all conspire to translates portions of a form. Do you have a repo that uses Flask-Security forms that you could share? or else would you be willing to answer some questions around how you configure your app (like are you using stock forms or extending them, any particular configuration around babel, etc?)
thanks.

**Pull request merged**
